
module RSpec
  module WellsFargoSpecHelpers
    def model
      ::MMA::Banks::WellsFargo
    end

    def arr
      [
        [nil, "CORRESPONDENT BEST EFFORT CONFORMING PRICING", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, "SRP NOT INCLUDED IN POSTED PRICE", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, "PRICE CODE:", 15966.0, nil, nil, "DATE:", 42866.0, nil, nil, nil, "EFFECTIVE TIME:", "08:00 AM CT", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "    PAGE 1 OF 9", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Prices are subject to change without notice.", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, "Lock/Registration Options: Available 24 / 7 (Except during price changes & from 7:30 AM CT until current day's pricing is posted)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Phone: Priceline Personnel are available 8:30 - 6:00 pm CST", nil, nil, nil, nil, nil, nil, nil, "wellsfargofunding.com", nil, nil, nil, nil, nil, nil],
        [nil, nil, "800.328.5074 Option 1, Option 2", nil, nil, nil, nil, nil, nil, "Fax:", "(866) 831-0407", nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "*Call For Mandatory Delivery Quotes*", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "Expiration Dates", nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7 DAY", "30 DAY", "45 DAY", "60 DAY", "70 DAY"],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, 42873.0, 42898.0, 42912.0, 42926.0, "N/A"],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "75 DAY", nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, 42941.0, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil],
        [nil, "CONFORMING CONVENTIONAL FIXED RATE  (SRP Not Included)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "30 YR FIXED", nil, nil, "20 YR FIXED", nil, nil, "15 YR FIXED", nil, nil, "10 YR FIXED", nil, nil, "30 YR FIXED RELO", nil, nil],
        [nil, "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY"],
        [nil, 3.25, 94.087, 93.834, 3.25, 96.455, 96.202, 2.75, 97.062, 96.856, 2.75, 97.437, 97.231, 3.25, 93.826, 93.573],
        [nil, 3.375, 94.996, 94.743, 3.375, 97.244, 96.991, 2.875, 97.619, 97.413, 2.875, 97.994, 97.788, 3.375, 94.735, 94.482],
        [nil, 3.5, 95.821, 95.568, 3.5, 97.96, 97.707, 3.0, 98.108, 97.902, 3.0, 98.483, 98.277, 3.5, 95.56, 95.307],
        [nil, 3.625, 96.587, 96.334, 3.625, 98.622, 98.369, 3.125, 98.543, 98.337, 3.125, 98.918, 98.712, 3.625, 96.326, 96.073, nil, nil, nil, nil],
        [nil, 3.75, 97.55, 97.297, 3.75, 99.407, 99.154, 3.25, 99.444, 99.238, 3.25, 99.819, 99.613, 3.75, 97.289, 97.036, nil, nil, nil, nil],
        [nil, 3.875, 98.236, 97.983, 3.875, 100.008, 99.755, 3.375, 99.976, 99.77, 3.375, 100.351, 100.145, 3.875, 97.975, 97.722, nil, nil, nil, nil],
        [nil, 4.0, 98.919, 98.666, 4.0, 100.604, 100.351, 3.5, 100.402, 100.196, 3.5, 100.777, 100.571, 4.0, 98.658, 98.405, nil, nil, nil, nil, nil],
        [nil, 4.125, 99.562, 99.309, 4.125, 101.164, 100.911, 3.625, 100.806, 100.6, 3.625, 101.181, 100.975, 4.125, 99.301, 99.048, nil, nil, nil, nil, nil],
        [nil, 4.25, 100.244, 99.991, 4.25, 101.899, 101.646, 3.75, 101.192, 100.986, 3.75, 101.567, 101.361, 4.25, 99.983, 99.73, nil, nil, nil, nil, nil],
        [nil, 4.375, 100.861, 100.608, 4.375, 102.441, 102.188, 3.875, 101.645, 101.439, 3.875, 102.02, 101.814, 4.375, 100.6, 100.347, nil, nil, nil, nil, nil],
        [nil, 4.5, 101.461, 101.208, 4.5, 102.965, 102.712, 4.0, 102.054, 101.848, 4.0, 102.429, 102.223, 4.5, 101.2, 100.947, nil, nil],
        [nil, 4.625, 102.042, 101.789, 4.625, 103.474, 103.221, 4.125, 102.437, 102.231, nil, nil, nil, 4.625, 101.781, 101.528, nil, nil],
        [nil, 4.75, 102.565, 102.312, 4.75, 103.926, 103.673, 4.25, 102.832, 102.626, nil, nil, nil, 4.75, 102.304, 102.051, nil, nil],
        [nil, 4.875, 103.141, 102.888, 4.875, 104.416, 104.163, 4.375, 103.178, 102.972, nil, nil, nil, 4.875, 102.88, 102.627, nil, nil],
        [nil, 5.0, 103.577, 103.324, 5.0, 104.727, 104.474, 4.5, 103.442, 103.236, nil, nil, nil, 5.0, 103.316, 103.063, nil, nil],
        [nil, 5.125, 104.286, 104.033, 5.125, 105.015, 104.762, nil, nil, nil, nil, nil, nil, 5.125, 104.025, 103.772],
        [nil, 5.25, 104.796, 104.543, 5.25, 105.452, 105.199, nil, nil, nil, nil, nil, nil, 5.25, 104.535, 104.282],
        [nil, 5.375, 105.183, 104.93, 5.375, 106.011, 105.758, nil, nil, nil, nil, nil, nil, 5.375, 104.922, 104.669],
        [nil, 5.5, 105.631, 105.378, 5.5, 106.338, 106.085, nil, nil, nil, nil, nil, nil, 5.5, 105.37, 105.117],
        [nil, 5.625, 106.508, 106.255, 5.625, 106.842, 106.589, nil, nil, nil, nil, nil, nil, 5.625, 106.247, 105.994],
        [nil, 5.75, 107.031, 106.778, 5.75, 107.261, 107.008, nil, nil, nil, nil, nil, nil, 5.75, 106.77, 106.517],
        [nil, 5.875, 107.417, 107.164, 5.875, 107.604, 107.351, nil, nil, nil, nil, nil, nil, 5.875, 107.156, 106.903],
        [nil, 6.0, 107.766, 107.513, 6.0, 107.925, 107.672, nil, nil, nil, nil, nil, nil, 6.0, 107.482, 107.229],
        [nil, 6.125, 108.039, 107.786, 6.125, 108.225, 107.972, nil, nil, nil, nil, nil, nil, 6.125, 107.711, 107.458],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Additional Lock Periods (Add to 60 day price)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, "7 DAY", "15 DAY", "45 DAY", "70 DAY", "75 DAY", nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "30 Yr", nil, 0.372, 0.372, 0.127, "N/A", -0.12, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "20 Yr", nil, 0.372, 0.372, 0.127, "N/A", -0.12, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "15 Yr", nil, 0.304, 0.304, 0.10899999999999999, "N/A", -0.093, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "30 Yr Relo", nil, 0.372, 0.372, 0.127, "N/A", -0.12, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "5/1 LIBOR", nil, 0.29300000000000004, 0.29300000000000004, 0.09500000000000001, "N/A", -0.08899999999999997, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "7/1 LIBOR", nil, 0.29300000000000004, 0.29300000000000004, 0.09500000000000001, "N/A", -0.08899999999999997, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "10/1 LIBOR", nil, 0.29300000000000004, 0.29300000000000004, 0.09500000000000001, "N/A", -0.08899999999999997, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "CONFORMING LIBOR ARMS (SRP Not Included)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "3/1 LIBOR ARM", nil, nil, "5/1 LIBOR ARM", nil, nil, "7/1 LIBOR ARM", nil, nil, "10/1 LIBOR ARM", nil, nil, nil, nil, nil, nil, nil],
        [nil, "2.25 margin & 2/2/6 cap", nil, nil, "2.25 margin & 2/2/5 cap", nil, nil, "2.25 margin & 5/2/5 cap", nil, nil, " 2.25 margin & 5/2/5 cap", nil, nil, nil, nil, nil, nil, nil],
        [nil, "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", "RATE", "30 DAY", "60 DAY", nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 2.25, 96.045, 95.846, 2.25, 94.64, 94.441, 2.5, 93.814, 93.615, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 2.375, 96.447, 96.248, 2.375, 95.105, 94.906, 2.625, 94.3, 94.101, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 2.5, 96.84599999999999, 96.64699999999999, 2.5, 95.568, 95.369, 2.75, 94.78399999999999, 94.585, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 2.625, 97.246, 97.047, 2.625, 96.033, 95.834, 2.875, 95.269, 95.07000000000001, nil, nil, nil, nil, nil], [nil, nil, nil, nil, 2.75, 97.647, 97.44800000000001, 2.75, 96.496, 96.297, 3.0, 95.755, 95.556, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 2.875, 98.047, 97.848, 2.875, 96.96, 96.761, 3.125, 96.239, 96.04, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.0, 98.44800000000001, 98.24900000000001, 3.0, 97.423, 97.224, 3.25, 96.75500000000001, 96.55600000000001, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.125, 98.84899999999999, 98.64999999999999, 3.125, 97.886, 97.687, 3.375, 97.27, 97.071, nil, nil, nil, nil, nil], [nil, nil, nil, nil, 3.25, 99.249, 99.05, 3.25, 98.349, 98.15, 3.5, 97.786, 97.587, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.375, 99.65, 99.45100000000001, 3.375, 98.812, 98.613, 3.625, 98.30099999999999, 98.10199999999999, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.5, 100.053, 99.854, 3.5, 99.27600000000001, 99.07700000000001, 3.75, 98.817, 98.618, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.625, 100.429, 100.23, 3.625, 99.739, 99.54, 3.875, 99.301, 99.102, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, 3.75, 100.77600000000001, 100.57700000000001, 3.75, 100.171, 99.97200000000001, 4.0, 99.75399999999999, 99.55499999999999, nil, nil, nil],
        [nil, nil, nil, nil, 3.875, 101.091, 100.892, 3.875, 100.604, 100.405, 4.125, 100.17699999999999, 99.978, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, 4.0, 101.00399999999999, 100.80499999999999, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, "For use by mortgage professionals only and should not be distributed to borrowers", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil], [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]
      ]
    end

    # def setup_parse_logic
    #   @mma_wf = double(model::WellsFargoLogic,
    #                    :conforming_pricing_array => arr,
    #                    :wf_worksheet_date => MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[2][7] ),
    #                    :wf_worksheet_price_code => arr[2][3].to_i.to_s,
    #                    :wf_worksheet_effective_time => arr[2][12],
    #                    :expiration_dates => { seven_day:        MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[14][11] ),
    #                                           thirty_day:       MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[14][12] ),
    #                                           fourty_five_day:  MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[14][13] ),
    #                                           sixty_day:        MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[14][14] ),
    #                                           seventy_day:      MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[14][15] ),
    #                                           seventy_five_day: MMA::Excel::ExcelUtils.parse_to_yyyy_mm_dd( arr[16][11] )
    #                        },
    #                    :wf_worksheet_conf_title_index => arr[20][1]
    #   )
    # end

    def self.conf_adjuster_arr
      [
        [" ", "CORRESPONDENT BEST EFFORT CONFORMING PRICE ADJUSTERS", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, "PRICE CODE:", 15966.0, "DATE:", 42866.0, nil, nil, nil, nil, nil, "EFFECTIVE TIME:", "08:00 AM CT", nil],
        [nil, "    PAGE 2 OF 9", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Only loans complying with the Seller Guide are permitted", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "CONFORMING FIXED AND ARM ADJUSTERS (If multiple adjusters apply, all adjusters must be used)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, "LTV %", "<=50.00", "50.01-\n70.00", "70.01-\n75.00", "75.01-\n80.00", "80.01-   85.00", "85.01-\n90.00", "90.01-\n95.00", "95.01-\n97.00", "97.01-\n100.00", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Investor", nil, nil, nil, nil, "FRM", -2.125, -2.125, -2.125, -3.375, -4.125, "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Attached Condos w/Term > 15 YR (>95 = DU Only)", nil, nil, nil, nil, "FRM", 0.0, 0.0, 0.0, -0.75, -0.75, -0.75, -0.75, -0.75, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "High LTVs >95%<=97% (DU version>= 8.2) Delegated only", nil, nil, nil, nil, "FRM", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", 0.0, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "2-Unit Property (>80% = FRM Only)", nil, nil, nil, nil, "FRM & ARM", -1.0, -1.0, -1.0, -1.0, -1.0, "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "3 & 4-Unit Property", nil, nil, nil, nil, "FRM & ARM", -1.0, -1.0, -1.0, -1.0, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Co-Op", nil, nil, nil, nil, "FRM & ARM", -0.25, -0.25, -0.25, -0.25, -0.25, -0.25, -0.25, "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Investor", nil, nil, nil, nil, "ARM", -2.125, -2.125, -2.125, -3.375, -4.125, "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Attached Condos", nil, nil, nil, nil, "ARM", 0.0, 0.0, 0.0, -0.75, -0.75, -0.75, -0.75, "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV >90% <= 95%  (w/LP)", nil, nil, nil, nil, " ARM", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.25, "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV >90%", nil, nil, nil, nil, "FRM/ARM (ARM N/A >95%)", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.125, -0.125, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Interest Only  (All I/O Term = 120 Months Only)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Interest Only ", nil, nil, nil, nil, "5/1, 7/1, 10/1 ARM", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Secondary Financing", nil, nil, nil, nil, nil, "FICO", "FICO", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV Ratios", nil, "CLTV** Ratios", nil, nil, nil, "<720", ">=720", "FICO Adjusters: Applicable to all Conforming Conv. Loans", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "<= 75%", nil, "<=80%", nil, nil, "FRM & ARM", -0.375, -0.375, "680-699", nil, "FRM/ARM", nil, 0.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "<= 65%", nil, "> 80% <= 95%", nil, nil, "FRM & ARM", -0.875, -0.625, "620-679", nil, "FRM/ARM", nil, 0.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "> 65% <= 75%", nil, "> 80% <= 95%", nil, nil, "FRM & ARM", -1.125, -0.875, "<620", nil, "FRM/ARM", nil, -1.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "> 75% <= 90% ", nil, "> 76% <= 90%", nil, nil, "FRM & ARM", -1.375, -1.125, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "> 75% <= 95%", nil, "> 90% <= 95%", nil, nil, "FRM & ARM", -1.375, -1.125, "< 620 LTV >70%", nil, "15 Yr FRM ", nil, -1.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "<= 95%", nil, "> 95% <= 97%", nil, nil, "FRM (DU Only)", -1.875, -1.875, "APPRAISAL ALTERNATIVE  ", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "(**) TLTV calculation used with HELOC", nil, nil, nil, nil, nil, nil, nil, "LP - PIA ", 50.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, "DU - PIW ", 0.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "(Adj. will not apply if the secondary financing is a Community Second loan.)", nil, nil, nil, nil, nil, nil, nil, "NOTE: PIW No Longer Charged With January Deliveries", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Conforming Extended Lock Up-front Fees (Non-refundable)", nil, nil, nil, nil, nil, nil, "Rate Financed Extended Lock Option (RFELO)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, "FRM", "ARM", nil, "FRM", "ARM", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Days", "Up-Front", "Up-Front", "Days", "Up-Front", "Up-Front", nil, "NOTE: Sellers must be authorized by their Regional Sales Executive", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, 90.0, 0.375, 0.375, 240.0, 1.75, "n/a", nil, "to use this program", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, 120.0, 0.625, 0.625, 270.0, 2.0, "n/a", nil, "- When locking through Wellsfargofunding.com, sellers must contact", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, 150.0, 0.875, 0.875, 300.0, 2.25, "n/a", nil, "   Priceline same day to apply the up-front fee and rate adjustment ", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, 180.0, 1.125, 1.125, 330.0, 2.5, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, 210.0, 1.5, "n/a", 360.0, 2.875, "n/a", nil, "Conforming FRM Products:", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, "Days", "Up-Front Fee (Non-Refundable)", nil, nil, nil, nil, "Rate Add-On", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "NOTE:  Conforming ARMs NA > 180 Days.", nil, nil, nil, nil, nil, nil, 120.0, 0.625, nil, nil, nil, nil, 0.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, 180.0, 1.0, nil, nil, nil, nil, 0.00125, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, 270.0, 1.0, nil, nil, nil, nil, 0.0025, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "TBD Property Lock Option:", nil, nil, nil, nil, nil, nil, 360.0, 1.0, nil, nil, nil, nil, 0.00375, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Add-on to the extended lock up-front fee (Non-Refundable)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Days*", nil, "Up-Front", nil, nil, nil, nil, "Conforming ARM Products:", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "90-360", nil, 0.125, nil, nil, nil, nil, "Days", "Up-Front Fee (Non-Refundable)", nil, nil, nil, nil, "Rate Add-On", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "(* Applicable to all extended locks where allowed by product)", nil, nil, nil, nil, nil, nil, 120.0, 0.625, nil, nil, nil, nil, 0.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, 180.0, 1.0, nil, nil, nil, nil, 0.00125, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, 270.0, "n/a", nil, nil, nil, nil, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, " Extensions, Late Delivery & Suspense (Conf. & Non Conf.)", nil, nil, nil, nil, nil, nil, 360.0, "n/a", nil, nil, nil, nil, "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "5 days = (.125)", nil, nil, "15 days= (.375)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "10 days= (.250)", nil, nil, "20 days= (.500)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "Daily adjuster = (.025)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "NOTE:  Add'l Late Del. fee of .125 will be assessed if the ", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "loan isn't extended prior to delivery expiration.", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "(*)  >95% Allowed w/DU Only", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "(#) Additional Adjusters Applicable with 18% Alt-MI Coverage. Allowed w/DU Only", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV%", nil, nil, nil, nil, nil, "<=60%", "60.01 - 70%", "70.01-75%", "75.01-80%", "80.01-85%", "85.01-90%", "90.01-95%", "*95.01-97%", "#95.01-97%", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV / FICO Adjusters: All Products w/Terms > 15 Yrs", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, ">=740", nil, nil, nil, nil, "FRM/ARM", 0.0, -0.25, -0.25, -0.5, -0.25, -0.25, -0.25, -0.75, -1.0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "720-739", nil, nil, nil, nil, "FRM/ARM", 0.0, -0.25, -0.5, -0.75, -0.5, -0.5, -0.5, -1.0, -1.25, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "700 - 719", nil, nil, nil, nil, "FRM/ARM", 0.0, -0.5, -1.0, -1.25, -1.0, -1.0, -1.0, -1.5, -1.25, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "680 - 699", nil, nil, nil, nil, "FRM/ARM", 0.0, -0.5, -1.25, -1.75, -1.5, -1.25, -1.25, -1.5, -1.75, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "660 - 679", nil, nil, nil, nil, "FRM/ARM", 0.0, -1.0, -2.25, -2.75, -2.75, -2.25, -2.25, -2.25, -2.125, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "640 - 659", nil, nil, nil, nil, "FRM/ARM", -0.5, -1.25, -2.75, -3.0, -3.25, -2.75, -2.75, -2.75, -2.375, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "620 - 639", nil, nil, nil, nil, "FRM/ARM", -0.5, -1.5, -3.0, -3.0, -3.25, -3.25, -3.25, -3.5, -2.75, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "<620", nil, nil, nil, nil, "FRM/ARM", -0.5, -1.5, -3.0, -3.0, -3.25, -3.25, -3.25, "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "LTV / FICO Adjusters: Cash-Out Refinance (All Terms)", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, ">=740", nil, nil, nil, nil, "FRM/ARM", -0.375, -0.625, -0.625, -0.875, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "720 - 739", nil, nil, nil, nil, "FRM/ARM", -0.375, -1.0, -1.0, -1.125, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "700 - 719", nil, nil, nil, nil, "FRM/ARM", -0.375, -1.0, -1.0, -1.125, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "680 - 699", nil, nil, nil, nil, "FRM/ARM", -0.375, -1.125, -1.125, -1.75, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "660 - 679", nil, nil, nil, nil, "FRM/ARM", -0.625, -1.125, -1.125, -1.875, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "640 - 659", nil, nil, nil, nil, "FRM/ARM", -0.625, -1.625, -1.625, -2.625, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "620 - 639", nil, nil, nil, nil, "FRM/ARM", -0.625, -1.625, -1.625, -3.125, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "<620", nil, nil, nil, nil, "FRM/ARM", -1.625, -2.625, -2.625, -3.125, "n/a", "n/a", "n/a", "n/a", "n/a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
        [nil, "For use by mortgage professionals only and should not be distributed to borrowers", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]
      ]
    end
  end
end
